# Generated by Django 3.2.4 on 2021-06-22 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('brand', models.CharField(max_length=256)),
                ('category', models.CharField(max_length=256)),
                ('retail_price', models.CharField(max_length=256)),
                ('selling_price', models.CharField(max_length=256)),
                ('rating', models.IntegerField()),
                ('arrival', models.DateField()),
            ],
        ),
    ]
